### ISSUE TITLE
Extracted Sprites.

### ISSUE THREAD

**Issue by LedLoaf** [polserver/UOFiddler#87]
Hello,

So I just found out about this software. I've been hoping to get a hold of UO sprites FOREVER. I was able to extract all the tiles and textures. But is there a way to extract all the enemies and items at the same time? It's going to take a long time to go through each one, hit animation, and then extract the frames. It would be great if I could just extract all and receive a folder of the enemy name with their sprites. I might look at the code and see if I can possibly do something myself, because it's the same thing with the sounds.

With that said, has anyone actually extracted all the content out and has it for download? That would be amazing. 

Thanks

EDIT: Wanted to add I just wanted the assets of UO, I'm not making a shard or anything. It was just awesome to see a way to actually get them.

EDIT2: Sorry I wanted to add, can anyone explain how people figured out how to make the UO server back in the day? It's just mind-blowing someone figured out how to do that. I just to play those free shards 15 years ago and I'm wondering if anything was ever provided by the developers to get that far.

**Comment by AsYlum-** [comment]
There is no universal button "Get me all assets". For Items, Textures, Land Tiles and Multis you can export all images from menu Misc -> Export all. There is no Export All for Animations. You can only export frames for animation in few different "formats". That's in Animations -> Settings -> Animation Edit then you have to choose animX.mul file and select animation slot and on the left list you can click right mouse button and select  Extract Images...

MUL or UOP files are optimized for storing uo data so you'll save a lot of disk space just keeping the client and extracting what you need when you need.

**Comment by LedLoaf** [comment]
> There is no universal button "Get me all assets". For Items, Textures, Land Tiles and Multis you can export all images from menu Misc -> Export all. There is no Export All for Animations. You can only export frames for animation in few different "formats". That's in Animations -> Settings -> Animation Edit then you have to choose animX.mul file and select animation slot and on the left list you can click right mouse button and select Extract Images...
> 
> MUL or UOP files are optimized for storing uo data so you'll save a lot of disk space just keeping the client and extracting what you need when you need.

Hey, 

I appreciate the response. I've been going to the animation editor and extracting them all one by one. Changing the directory folder to a new one each time (1. Ogre, 2. Ettin, etc..). **I have another question if you don't mind?**

_**Some of the animations I can view under the animation tab, looking at all the directions and actions. But under the animation editor, where I extract them, they are red and nothing appears? How can I get these files enabled?**_ 

For instance:
 **11. Arachnid Spider Dread, 
19. Arachnid Spider Dread2, 
20. Arachnid Spider Frost, 
23. Wolf Dire, 
25. Wolf Grey,
26. Spirits Ghost, 
27. Wolf Grey2, 
34. Wolf White, 
37. Wolf White2, 
38. Daemon Blackgate
40. Daemon Elder**

I've doing 50 a day and those are all missing from the first 50 under the animation editor. The animation tab shows them though and unfortunately, you can't export each frame from there unless you make a folder for each new piece, because for instance, it will do "Mob 40.png" for the first frame and moving the frame to the 2nd it will just overwrite it with the same name. So I have to read it under the animation editor and not the tab. It would be cool if I could rename each export I have to do like that, unfortunately, I'm not very familiar with C#. 

Any help would be appreciated. 

Thanks.

**PS: I guess the TLDR; would be what can I download to make sure I have all the content this software can access? (Clients etc)**

**Comment by AsYlum-** [comment]
That is a bit more complicated. Animations are mapped to one of 2048 slots called body id. But data for animations is located in files anim1-5.mul. In later clients (version>7) there are also animations in .uop format but that is not supported in UOFiddler at the moment. So when you open animation edit you can view "raw" animation data for given animX.mul file.

Animations tab shows you mapped slots from anim1-5.mul into the main body id list. If you hover over that animation of "arachnid dread" it will show you tooltip with information from which animX.mul file it is mapped. Mappings are defined mainly in body.def and bodyconv.def.

![image](https://user-images.githubusercontent.com/377468/122549231-8dbf5180-d032-11eb-9c5c-d6662af3b9c3.png)

UO has multiple animation types and each type differs so not all of them have full list of actions. They also have different amount of frames. So the red indicator tells you that this slot/action item has no data in it. For example animals (L) have the lowest count of frames and actions and People/Equipment (P) has the highest. Mosters (H) and sea monsters are somewhere in between. On top of that there are some conventions in anim.mul files when it comes to storing data and that can be partially overridden with mobtypes.txt flags. 

So all in all if you export wolf animation it will have less frames than for example human body.

The animation control and editor form will be updated in future but I can't tell you when. Right now you have to define proper animationlist.xml as the one shipped with fiddler may not be 100% correct. Problem is time :) Last few months I don't have enough free time to work on this.

You will also have to look for format definition for .mul files and additional info how animations work in uo clients because writing all of this in detail will take me too much time ;) you can find a lot of information on servuo forums.

**Comment by LedLoaf** [comment]
> You will also have to look for format definition for .mul files and additional info how animations work in uo clients because writing all of this in detail will take me too much time ;) you can find a lot of information on servuo forums.

Hey!

I appreciate the long response and explaining it a bit. Okay, that makes a lot more sense that it is reading from anim2. I wasn't quite sure what that list was about (1-5). Yeah, I realized that it seems it expects each animation to have 21 animation events, but like you said some don't require that much. For example the Gargoyle seems to have the expanded amount (21), since it has flying behavior as well.

I appreciate you taking the time! I find the project fascinating in general and how it was even reversed engineered to begin with and the servers etc.. Selfishly, I just want all the sprites from UO, so that's my goal haha and I've looked for them forever (expecting them to be released by someone) and I don't even know how I went down this rabbit hole recently. 

**One last thing, why did you remove the .png format from the extract all command from the animation editor?* I added it into the project, but I noticed when I use it but instead of 6,000 (bmp) sprites (not being exact/accurate here) I'll only get half of them. So it's obviously not hooked up right from myself and I was wondering if there was a reason in general that you left png out on that portion?

Lastly, I understand you don't have the time and probably even motivation to continue this project. I'm sure this game is basically dead at this point, despite even 5-8 years ago still having decent size free shards! Would it be to hard (too much) to get a snippet of code to add just so I can extract all these animation files? I don't know C#, but I can read what's going on for the most part. But if this is already too much work, I don't even want to go down that road in learning it to accomplish something already difficult haha. But I find this project very important educationally and preserving content from such a classic gem.

Thanks, have a great weekend.

**Comment by AsYlum-** [comment]
This isn't dead project. Currently I'm only maintainer with very limited amount of time to work on this and most of that time is going into creating a bit better UI and Ultima SDK library that will be released somewhere in future. Most of the features needed are already here so there are no major changes planned but we are open for contributions ;) 

I don't remember removing .png from animations probably it was never there or it has something to do with frame format. I'll look into this later.

When it comes to snippet I can't give you one from top of my head but if I find free hour I can try to add this.

**Comment by sandro** [comment]
@LedLoaf Did you ever figure out a way to bulk extract assets?
